project:
  type: website
  output-dir: _output
  render:
    #- "*.qmd"
    - pages/lectures/*.qmd
    - pages/background/*.qmd
    - pages/misc/*.qmd
    - pages/slides/*.qmd
    - "index.qmd"
    - "!NOTES.md"
    - "!demos/*"

author: "Marco Willi"
affiliation: "Institute for Data Science I4DS, FHNW"

execute:
  freeze: True

pdf-engine: xelatex

website:
  page-navigation: true
  title: "CAS Deep Learning - Computer Vision"
  description: "Homepage for CAS Deep Learning - Computer Vision (Part1) with reading materials and exercises"
  favicon: "/assets/cv_logo_small.png"

  site-url: "https://marco-willi.github.io/cas-dl-compvis-lectures-hs2025/"
  repo-url: https://github.com/marco-willi/cas-dl-compvis-lectures-hs2025
  repo-actions: [issue]

  google-analytics: "G-97BR3FTSN1"

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2025, Marco Willi"
    #background: "#D9E3E4"

  sidebar:
    logo: "/assets/cv_logo_small.png"
    pinned: true
    search: true
    align: center
    style: "docked"
    collapse-level: 1
    tools:
      - icon: github
        href: https://github.com/marco-willi/cas-dl-compvis-lectures-hs2025
        text: "GitHub organization"
      - icon: code-square

    contents:
      - text: "Home"
        href: index.qmd
      # ------ Background & Preparation------------ #
      - section: Background & Preparation
        contents:
          - pages/background/machine_learning.qmd
          - pages/background/neural_networks.qmd
          - pages/background/frameworks.qmd
      # ------ Lecture ---------------------------- #
      - section: Lectures
        contents:
          - pages/lectures/intro.qmd
          - pages/lectures/cnns.qmd
          - pages/lectures/classification.qmd
          - pages/lectures/representation_learning.qmd
          - pages/lectures/practical.qmd
          - pages/lectures/recent_advances.qmd
      # ------ SLIDES ---------------------------- #
      - section: Slides
        contents:
          - pages/slides/intro.qmd
          - pages/slides/cnns.qmd
          - pages/slides/image_classification.qmd
          - pages/slides/representation_learning.qmd
          - pages/slides/practical.qmd
          - pages/slides/recent_advances.qmd
      # ------ Exercises ---------------------------- #
      - text: "Exercises"
        href: pages/misc/exercises.qmd
      # ------ Quiz & Exam Prep---------------------------- #
      - text: "Quiz & Exam Prep"
        href: pages/misc/quiz.qmd

      # ------ Misc ---------------------------- #
      - section: Resources
        contents:
          - pages/misc/literature.qmd
          - pages/misc/links.qmd
          - pages/misc/notation.qmd
          - pages/misc/student_projects.qmd

bibliography: assets/references.bib

institute: "Institute for Data Science I4DS, FHNW"

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    code-fold: false
    code-tools: true
    highlight-style: github
  # pdf:
  #   include-in-header:
  #     - "./assets/_macros.tex"
